version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cross-fetch
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: xmldom
    versions:
    - 0.5.0
